import Head from "next/head";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Header from "../components/Header/Header";
import Works from "../components/Works/Works";
import Footer from "../components/footer/Footer";
import { useEffect } from "react";
import Background from "../components/Ui/Background";

import HeaderLinks from "../components/Header/HeaderLinks/HeaderLinks";

export default function Home() {
  useEffect(() => {
    let rn = Math.floor(Math.random() * 150 + 60);
    let rs = Math.floor(Math.random() * 11 + 4);

    const pattern = trianglify({
      xColors: ["#fff", "#28345A"],
      // yColors: 'matchX',
      width: document.documentElement.clientWidth ,
      height: document.documentElement.scrollHeight,
      // noiseIntensity: 0,
      cellSize: rn,
      // colorFunction: false,
    });
    document.body.appendChild(pattern.toCanvas());
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Background /> */}
      <HeaderLinks />
      <Header />
      <About />
      <Works />
      <Contact />
      <Footer />
    </>
  );
}
