import Head from "next/head";
import Image from "next/image";
import About from "../components/About/About";
import Header from "../components/Header/Header";
import Works from "../components/Works/Works";

import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Works />
    </>
  );
}
